# -*- coding: utf-8 -*-
"""tarefa2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f7YQy3emYgfrpmvrmeRU8tgKsuB2rKIJ
"""

import networkx as nx
import matplotlib.pyplot as plt
from gerarGrafoDeAeroportosERotas import gerarGrafoDeAeroportosERotas
import sys

dadosDoGrafo = gerarGrafoDeAeroportosERotas()
grafo_silver = dadosDoGrafo["GrafoDeAeroportosERotas"]

#métricas básicas
graus = dict(grafo_silver.degree()).values()
grau_medio = sum(graus) / len(grafo_silver.nodes())
conec_vert = nx.node_connectivity(grafo_silver)
conec_arest = nx.edge_connectivity(grafo_silver)

#Diâmetro e Excentricidade, conectividade
if nx.is_connected(grafo_silver):
    status_conexao = "Conexo"
    diametro = nx.diameter(grafo_silver)
    excentricidade_max = max(nx.eccentricity(grafo_silver).values())
else:
    status_conexao = "Desconexo"
    maior_componente = max(nx.connected_components(grafo_silver), key=len)
    subgrafo = grafo_silver.subgraph(maior_componente)
    diametro = f"{nx.diameter(subgrafo)} (Maior Comp.)"
    excentricidade_max = f"{max(nx.eccentricity(subgrafo).values())} (Maior Comp.)"

#tabela (matriz)
dados_tabela = [
    ["Métrica", "Resultado"],
    ["Status da Rede", status_conexao],
    ["Grau Médio dos Vértices", f"{grau_medio:.2f}"],
    ["Conectividade de Vértices", str(conec_vert)],
    ["Conectividade de Arestas", str(conec_arest)],
    ["Diâmetro do Grafo", str(diametro)],
    ["Excentricidade Máxima", str(excentricidade_max)]
]

#Matplotlib, tabela
fig, ax = plt.subplots(figsize=(8, 4))
ax.axis('off')
tabela = ax.table(cellText=dados_tabela, loc='center', cellLoc='center', colWidths=[0.5, 0.3])
tabela.auto_set_font_size(False)
tabela.set_fontsize(12)
tabela.scale(1, 2)
for j in range(2):
    tabela[(0, j)].set_facecolor('#e0e0e0')
    tabela[(0, j)].set_text_props(weight='bold')
plt.title("Métricas da Rede - Silver Airways (3M)", fontweight="bold", fontsize=14, y=0.95)

plt.savefig("images/metricasDaRede.jpg", dpi=600)
plt.show()

#Para testarmos a validade da análise, a célula abaixo roda o mesmo código para um grafo quadrado de 2x2 com vértices A, B, C e D. Portanto, todas as métricas devem ter valor 2:
if "validar" in sys.argv:
    import networkx as nx
    import matplotlib.pyplot as plt
    
    #descrição do grafo
    grafo_silver = nx.Graph()
    grafo_silver.add_edges_from([('A', 'B'), ('B', 'C'), ('C', 'D'), ('D', 'A')])
    
    #exato mesmo código:
    
    #métricas básicas
    graus = dict(grafo_silver.degree()).values()
    grau_medio = sum(graus) / len(grafo_silver.nodes())
    conec_vert = nx.node_connectivity(grafo_silver)
    conec_arest = nx.edge_connectivity(grafo_silver)
    
    #Diâmetro e Excentricidade, conectividade
    if nx.is_connected(grafo_silver):
        status_conexao = "Conexo"
        diametro = nx.diameter(grafo_silver)
        excentricidade_max = max(nx.eccentricity(grafo_silver).values())
    else:
        status_conexao = "Desconexo"
        maior_componente = max(nx.connected_components(grafo_silver), key=len)
        subgrafo = grafo_silver.subgraph(maior_componente)
        diametro = f"{nx.diameter(subgrafo)} (Maior Comp.)"
        excentricidade_max = f"{max(nx.eccentricity(subgrafo).values())} (Maior Comp.)"
    
    #tabela (matriz)
    dados_tabela = [
        ["Métrica", "Resultado"],
        ["Status da Rede", status_conexao],
        ["Grau Médio dos Vértices", f"{grau_medio:.2f}"],
        ["Conectividade de Vértices", str(conec_vert)],
        ["Conectividade de Arestas", str(conec_arest)],
        ["Diâmetro do Grafo", str(diametro)],
        ["Excentricidade Máxima", str(excentricidade_max)]
    ]
    
    #Matplotlib, tabela
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.axis('off')
    tabela = ax.table(cellText=dados_tabela, loc='center', cellLoc='center', colWidths=[0.5, 0.3])
    tabela.auto_set_font_size(False)
    tabela.set_fontsize(12)
    tabela.scale(1, 2)
    for j in range(2):
        tabela[(0, j)].set_facecolor('#e0e0e0')
        tabela[(0, j)].set_text_props(weight='bold')
    plt.title("Métricas da Rede - Prova Real com grafo quadrado", fontweight="bold", fontsize=14, y=0.95)
    
    plt.savefig("images/metricasDaRede2x2.jpg", dpi=600)
    plt.show()
